# -*- coding: utf-8 -*-
"""irisdatamodelml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19gLAidDszjmqdIrEOVmDAIVgv6LCO8rJ

IRIS DATA CLASSIFICATION USING 3 DISTINCT MODELS

Importing libraries
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
# %matplotlib inline

"""Loading the dataset"""

import pandas as pd

url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/iris.csv'
df = pd.read_csv(url)

df.columns = ['Sepal length', 'Sepal width', 'Petal length', 'Petal width', 'Species']

df.head()

"""Visualize dataset"""

df.describe()

sns.pairplot(df, hue='Species')

"""Seperating inpput and output columns"""

data = df.values
X = data[:,0:4]
Y = data[:,4]

"""Splitting data into training and testing"""

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

"""MODEL 1: Support vector machine algorithm"""

from sklearn.svm import SVC
model_svc = SVC()
model_svc.fit(X_train, Y_train)

prediction1 = model_svc.predict(X_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test, prediction1)*100)
for i in range (len(prediction1)):
  print (Y_test[i], prediction1[i])

"""MODEL 2: Logistic Regression"""

from sklearn.linear_model import LogisticRegression
model_LR=LogisticRegression()
model_LR.fit(X_train, Y_train)

prediction2 = model_LR.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test, prediction2)*100)
for i in range (len(prediction1)):
  print (Y_test[i], prediction1[i])

"""MODEL 3: Decision Tree Classifier"""

from sklearn.tree import DecisionTreeClassifier
model_DTC=DecisionTreeClassifier()
model_DTC.fit(X_train, Y_train)

prediction3 = model_DTC.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test, prediction3)*100)
for i in range (len(prediction3)):
  print (Y_test[i], prediction3[i])