# -*- coding: utf-8 -*-
"""irisdatamodelml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19gLAidDszjmqdIrEOVmDAIVgv6LCO8rJ

IRIS DATA CLASSIFICATION USING 3 DISTINCT MODELS

Importing libraries
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

# Load dataset
url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/iris.csv'
df = pd.read_csv(url)
df.columns = ['Sepal length', 'Sepal width', 'Petal length', 'Petal width', 'Species']

# Split features & labels
X = df.iloc[:, 0:4].values
Y = df.iloc[:, 4].values

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Train models
svm_model = SVC(probability=True)
svm_model.fit(X_train, Y_train)

logreg_model = LogisticRegression(max_iter=200)
logreg_model.fit(X_train, Y_train)

tree_model = DecisionTreeClassifier()
tree_model.fit(X_train, Y_train)

# Label names
class_names = sorted(df['Species'].unique())
